export const SHOW_MOBILE_MENU = 'SHOW_MOBILE_MENU';
export const SHOW_MODAL = 'SHOW_MODAL';

export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAIL = 'GET_GAMES_FAIL';
export const GET_GAMES_LOADING = 'GET_GAMES_LOADING';

export const GET_STADISTICS_SUCCESS = 'GET_STADISTICS_SUCCESS';
export const GET_STADISTICS_FAIL = 'GET_STADISTICS_FAIL';
export const GET_STADISTICS_LOADING = 'GET_STADISTICS_LOADING';
export const SAVE_STADISTICS_SUCCESS = 'SAVE_STADISTICS_SUCCESS';
export const SAVE_STADISTICS_FAIL = 'SAVE_STADISTICS_FAIL';
export const SAVE_STADISTICS_LOADING = 'SAVE_STADISTICS_LOADING';

export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_FAIL = 'GET_PLAYERS_FAIL';
export const GET_PLAYERS_LOADING = 'GET_PLAYERS_LOADING';
export const SET_SELECTED_PLAYER = 'SET_SELECTED_PLAYER';
