export const SHOW_MOBILE_MENU = 'SHOW_MOBILE_MENU';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAIL = 'GET_GAMES_FAIL';
export const GET_GAMES_LOADING = 'GET_GAMES_LOADING';
